# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: LoadBalancer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='LoadBalancer.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12LoadBalancer.proto\"(\n\x11LoadBalancerState\x12\x13\n\x0b\x62\x61lancer_on\x18\x01 \x01(\x08\x42\x45\n*org.apache.hadoop.hbase.protobuf.generatedB\x12LoadBalancerProtosH\x01\xa0\x01\x01')
)




_LOADBALANCERSTATE = _descriptor.Descriptor(
  name='LoadBalancerState',
  full_name='LoadBalancerState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='balancer_on', full_name='LoadBalancerState.balancer_on', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=62,
)

DESCRIPTOR.message_types_by_name['LoadBalancerState'] = _LOADBALANCERSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LoadBalancerState = _reflection.GeneratedProtocolMessageType('LoadBalancerState', (_message.Message,), dict(
  DESCRIPTOR = _LOADBALANCERSTATE,
  __module__ = 'LoadBalancer_pb2'
  # @@protoc_insertion_point(class_scope:LoadBalancerState)
  ))
_sym_db.RegisterMessage(LoadBalancerState)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\022LoadBalancerProtosH\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
