# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MapReduce.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import HBase_pb2 as HBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='MapReduce.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0fMapReduce.proto\x1a\x0bHBase.proto\".\n\x0bScanMetrics\x12\x1f\n\x07metrics\x18\x01 \x03(\x0b\x32\x0e.NameInt64Pair\"g\n\x18TableSnapshotRegionSplit\x12\x11\n\tlocations\x18\x02 \x03(\t\x12\x1b\n\x05table\x18\x03 \x01(\x0b\x32\x0c.TableSchema\x12\x1b\n\x06region\x18\x04 \x01(\x0b\x32\x0b.RegionInfoBB\n*org.apache.hadoop.hbase.protobuf.generatedB\x0fMapReduceProtosH\x01\xa0\x01\x01')
  ,
  dependencies=[HBase__pb2.DESCRIPTOR,])




_SCANMETRICS = _descriptor.Descriptor(
  name='ScanMetrics',
  full_name='ScanMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='metrics', full_name='ScanMetrics.metrics', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=78,
)


_TABLESNAPSHOTREGIONSPLIT = _descriptor.Descriptor(
  name='TableSnapshotRegionSplit',
  full_name='TableSnapshotRegionSplit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='locations', full_name='TableSnapshotRegionSplit.locations', index=0,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='table', full_name='TableSnapshotRegionSplit.table', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region', full_name='TableSnapshotRegionSplit.region', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=183,
)

_SCANMETRICS.fields_by_name['metrics'].message_type = HBase__pb2._NAMEINT64PAIR
_TABLESNAPSHOTREGIONSPLIT.fields_by_name['table'].message_type = HBase__pb2._TABLESCHEMA
_TABLESNAPSHOTREGIONSPLIT.fields_by_name['region'].message_type = HBase__pb2._REGIONINFO
DESCRIPTOR.message_types_by_name['ScanMetrics'] = _SCANMETRICS
DESCRIPTOR.message_types_by_name['TableSnapshotRegionSplit'] = _TABLESNAPSHOTREGIONSPLIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ScanMetrics = _reflection.GeneratedProtocolMessageType('ScanMetrics', (_message.Message,), dict(
  DESCRIPTOR = _SCANMETRICS,
  __module__ = 'MapReduce_pb2'
  # @@protoc_insertion_point(class_scope:ScanMetrics)
  ))
_sym_db.RegisterMessage(ScanMetrics)

TableSnapshotRegionSplit = _reflection.GeneratedProtocolMessageType('TableSnapshotRegionSplit', (_message.Message,), dict(
  DESCRIPTOR = _TABLESNAPSHOTREGIONSPLIT,
  __module__ = 'MapReduce_pb2'
  # @@protoc_insertion_point(class_scope:TableSnapshotRegionSplit)
  ))
_sym_db.RegisterMessage(TableSnapshotRegionSplit)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\017MapReduceProtosH\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
