# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RowProcessor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RowProcessor.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x12RowProcessor.proto\"\xb1\x01\n\x0eProcessRequest\x12 \n\x18row_processor_class_name\x18\x01 \x02(\t\x12.\n&row_processor_initializer_message_name\x18\x02 \x01(\t\x12)\n!row_processor_initializer_message\x18\x03 \x01(\x0c\x12\x13\n\x0bnonce_group\x18\x04 \x01(\x04\x12\r\n\x05nonce\x18\x05 \x01(\x04\"/\n\x0fProcessResponse\x12\x1c\n\x14row_processor_result\x18\x01 \x02(\x0c\x32\x43\n\x13RowProcessorService\x12,\n\x07Process\x12\x0f.ProcessRequest\x1a\x10.ProcessResponseBH\n*org.apache.hadoop.hbase.protobuf.generatedB\x12RowProcessorProtosH\x01\x88\x01\x01\xa0\x01\x01')
)




_PROCESSREQUEST = _descriptor.Descriptor(
  name='ProcessRequest',
  full_name='ProcessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row_processor_class_name', full_name='ProcessRequest.row_processor_class_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row_processor_initializer_message_name', full_name='ProcessRequest.row_processor_initializer_message_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='row_processor_initializer_message', full_name='ProcessRequest.row_processor_initializer_message', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce_group', full_name='ProcessRequest.nonce_group', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nonce', full_name='ProcessRequest.nonce', index=4,
      number=5, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=200,
)


_PROCESSRESPONSE = _descriptor.Descriptor(
  name='ProcessResponse',
  full_name='ProcessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='row_processor_result', full_name='ProcessResponse.row_processor_result', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=202,
  serialized_end=249,
)

DESCRIPTOR.message_types_by_name['ProcessRequest'] = _PROCESSREQUEST
DESCRIPTOR.message_types_by_name['ProcessResponse'] = _PROCESSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ProcessRequest = _reflection.GeneratedProtocolMessageType('ProcessRequest', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSREQUEST,
  __module__ = 'RowProcessor_pb2'
  # @@protoc_insertion_point(class_scope:ProcessRequest)
  ))
_sym_db.RegisterMessage(ProcessRequest)

ProcessResponse = _reflection.GeneratedProtocolMessageType('ProcessResponse', (_message.Message,), dict(
  DESCRIPTOR = _PROCESSRESPONSE,
  __module__ = 'RowProcessor_pb2'
  # @@protoc_insertion_point(class_scope:ProcessResponse)
  ))
_sym_db.RegisterMessage(ProcessResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\022RowProcessorProtosH\001\210\001\001\240\001\001'))

_ROWPROCESSORSERVICE = _descriptor.ServiceDescriptor(
  name='RowProcessorService',
  full_name='RowProcessorService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=251,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='Process',
    full_name='RowProcessorService.Process',
    index=0,
    containing_service=None,
    input_type=_PROCESSREQUEST,
    output_type=_PROCESSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROWPROCESSORSERVICE)

DESCRIPTOR.services_by_name['RowProcessorService'] = _ROWPROCESSORSERVICE

# @@protoc_insertion_point(module_scope)
