# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SecureBulkLoad.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import HBase_pb2 as HBase__pb2
from . import Client_pb2 as Client__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SecureBulkLoad.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x14SecureBulkLoad.proto\x1a\x0bHBase.proto\x1a\x0c\x43lient.proto\"\xa4\x01\n\x1bSecureBulkLoadHFilesRequest\x12\x35\n\x0b\x66\x61mily_path\x18\x01 \x03(\x0b\x32 .BulkLoadHFileRequest.FamilyPath\x12\x16\n\x0e\x61ssign_seq_num\x18\x02 \x01(\x08\x12\"\n\x08\x66s_token\x18\x03 \x02(\x0b\x32\x10.DelegationToken\x12\x12\n\nbulk_token\x18\x04 \x02(\t\".\n\x1cSecureBulkLoadHFilesResponse\x12\x0e\n\x06loaded\x18\x01 \x02(\x08\"V\n\x0f\x44\x65legationToken\x12\x12\n\nidentifier\x18\x01 \x01(\x0c\x12\x10\n\x08password\x18\x02 \x01(\x0c\x12\x0c\n\x04kind\x18\x03 \x01(\t\x12\x0f\n\x07service\x18\x04 \x01(\t\"8\n\x16PrepareBulkLoadRequest\x12\x1e\n\ntable_name\x18\x01 \x02(\x0b\x32\n.TableName\"-\n\x17PrepareBulkLoadResponse\x12\x12\n\nbulk_token\x18\x01 \x02(\t\",\n\x16\x43leanupBulkLoadRequest\x12\x12\n\nbulk_token\x18\x01 \x02(\t\"\x19\n\x17\x43leanupBulkLoadResponse2\xf8\x01\n\x15SecureBulkLoadService\x12\x44\n\x0fPrepareBulkLoad\x12\x17.PrepareBulkLoadRequest\x1a\x18.PrepareBulkLoadResponse\x12S\n\x14SecureBulkLoadHFiles\x12\x1c.SecureBulkLoadHFilesRequest\x1a\x1d.SecureBulkLoadHFilesResponse\x12\x44\n\x0f\x43leanupBulkLoad\x12\x17.CleanupBulkLoadRequest\x1a\x18.CleanupBulkLoadResponseBJ\n*org.apache.hadoop.hbase.protobuf.generatedB\x14SecureBulkLoadProtosH\x01\x88\x01\x01\xa0\x01\x01')
  ,
  dependencies=[HBase__pb2.DESCRIPTOR,Client__pb2.DESCRIPTOR,])




_SECUREBULKLOADHFILESREQUEST = _descriptor.Descriptor(
  name='SecureBulkLoadHFilesRequest',
  full_name='SecureBulkLoadHFilesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='family_path', full_name='SecureBulkLoadHFilesRequest.family_path', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assign_seq_num', full_name='SecureBulkLoadHFilesRequest.assign_seq_num', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fs_token', full_name='SecureBulkLoadHFilesRequest.fs_token', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bulk_token', full_name='SecureBulkLoadHFilesRequest.bulk_token', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=216,
)


_SECUREBULKLOADHFILESRESPONSE = _descriptor.Descriptor(
  name='SecureBulkLoadHFilesResponse',
  full_name='SecureBulkLoadHFilesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loaded', full_name='SecureBulkLoadHFilesResponse.loaded', index=0,
      number=1, type=8, cpp_type=7, label=2,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=218,
  serialized_end=264,
)


_DELEGATIONTOKEN = _descriptor.Descriptor(
  name='DelegationToken',
  full_name='DelegationToken',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='identifier', full_name='DelegationToken.identifier', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='DelegationToken.password', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kind', full_name='DelegationToken.kind', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service', full_name='DelegationToken.service', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=352,
)


_PREPAREBULKLOADREQUEST = _descriptor.Descriptor(
  name='PrepareBulkLoadRequest',
  full_name='PrepareBulkLoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='table_name', full_name='PrepareBulkLoadRequest.table_name', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=410,
)


_PREPAREBULKLOADRESPONSE = _descriptor.Descriptor(
  name='PrepareBulkLoadResponse',
  full_name='PrepareBulkLoadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bulk_token', full_name='PrepareBulkLoadResponse.bulk_token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=457,
)


_CLEANUPBULKLOADREQUEST = _descriptor.Descriptor(
  name='CleanupBulkLoadRequest',
  full_name='CleanupBulkLoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='bulk_token', full_name='CleanupBulkLoadRequest.bulk_token', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=459,
  serialized_end=503,
)


_CLEANUPBULKLOADRESPONSE = _descriptor.Descriptor(
  name='CleanupBulkLoadResponse',
  full_name='CleanupBulkLoadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=505,
  serialized_end=530,
)

_SECUREBULKLOADHFILESREQUEST.fields_by_name['family_path'].message_type = Client__pb2._BULKLOADHFILEREQUEST_FAMILYPATH
_SECUREBULKLOADHFILESREQUEST.fields_by_name['fs_token'].message_type = _DELEGATIONTOKEN
_PREPAREBULKLOADREQUEST.fields_by_name['table_name'].message_type = HBase__pb2._TABLENAME
DESCRIPTOR.message_types_by_name['SecureBulkLoadHFilesRequest'] = _SECUREBULKLOADHFILESREQUEST
DESCRIPTOR.message_types_by_name['SecureBulkLoadHFilesResponse'] = _SECUREBULKLOADHFILESRESPONSE
DESCRIPTOR.message_types_by_name['DelegationToken'] = _DELEGATIONTOKEN
DESCRIPTOR.message_types_by_name['PrepareBulkLoadRequest'] = _PREPAREBULKLOADREQUEST
DESCRIPTOR.message_types_by_name['PrepareBulkLoadResponse'] = _PREPAREBULKLOADRESPONSE
DESCRIPTOR.message_types_by_name['CleanupBulkLoadRequest'] = _CLEANUPBULKLOADREQUEST
DESCRIPTOR.message_types_by_name['CleanupBulkLoadResponse'] = _CLEANUPBULKLOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SecureBulkLoadHFilesRequest = _reflection.GeneratedProtocolMessageType('SecureBulkLoadHFilesRequest', (_message.Message,), dict(
  DESCRIPTOR = _SECUREBULKLOADHFILESREQUEST,
  __module__ = 'SecureBulkLoad_pb2'
  # @@protoc_insertion_point(class_scope:SecureBulkLoadHFilesRequest)
  ))
_sym_db.RegisterMessage(SecureBulkLoadHFilesRequest)

SecureBulkLoadHFilesResponse = _reflection.GeneratedProtocolMessageType('SecureBulkLoadHFilesResponse', (_message.Message,), dict(
  DESCRIPTOR = _SECUREBULKLOADHFILESRESPONSE,
  __module__ = 'SecureBulkLoad_pb2'
  # @@protoc_insertion_point(class_scope:SecureBulkLoadHFilesResponse)
  ))
_sym_db.RegisterMessage(SecureBulkLoadHFilesResponse)

DelegationToken = _reflection.GeneratedProtocolMessageType('DelegationToken', (_message.Message,), dict(
  DESCRIPTOR = _DELEGATIONTOKEN,
  __module__ = 'SecureBulkLoad_pb2'
  # @@protoc_insertion_point(class_scope:DelegationToken)
  ))
_sym_db.RegisterMessage(DelegationToken)

PrepareBulkLoadRequest = _reflection.GeneratedProtocolMessageType('PrepareBulkLoadRequest', (_message.Message,), dict(
  DESCRIPTOR = _PREPAREBULKLOADREQUEST,
  __module__ = 'SecureBulkLoad_pb2'
  # @@protoc_insertion_point(class_scope:PrepareBulkLoadRequest)
  ))
_sym_db.RegisterMessage(PrepareBulkLoadRequest)

PrepareBulkLoadResponse = _reflection.GeneratedProtocolMessageType('PrepareBulkLoadResponse', (_message.Message,), dict(
  DESCRIPTOR = _PREPAREBULKLOADRESPONSE,
  __module__ = 'SecureBulkLoad_pb2'
  # @@protoc_insertion_point(class_scope:PrepareBulkLoadResponse)
  ))
_sym_db.RegisterMessage(PrepareBulkLoadResponse)

CleanupBulkLoadRequest = _reflection.GeneratedProtocolMessageType('CleanupBulkLoadRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLEANUPBULKLOADREQUEST,
  __module__ = 'SecureBulkLoad_pb2'
  # @@protoc_insertion_point(class_scope:CleanupBulkLoadRequest)
  ))
_sym_db.RegisterMessage(CleanupBulkLoadRequest)

CleanupBulkLoadResponse = _reflection.GeneratedProtocolMessageType('CleanupBulkLoadResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLEANUPBULKLOADRESPONSE,
  __module__ = 'SecureBulkLoad_pb2'
  # @@protoc_insertion_point(class_scope:CleanupBulkLoadResponse)
  ))
_sym_db.RegisterMessage(CleanupBulkLoadResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\024SecureBulkLoadProtosH\001\210\001\001\240\001\001'))

_SECUREBULKLOADSERVICE = _descriptor.ServiceDescriptor(
  name='SecureBulkLoadService',
  full_name='SecureBulkLoadService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=533,
  serialized_end=781,
  methods=[
  _descriptor.MethodDescriptor(
    name='PrepareBulkLoad',
    full_name='SecureBulkLoadService.PrepareBulkLoad',
    index=0,
    containing_service=None,
    input_type=_PREPAREBULKLOADREQUEST,
    output_type=_PREPAREBULKLOADRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SecureBulkLoadHFiles',
    full_name='SecureBulkLoadService.SecureBulkLoadHFiles',
    index=1,
    containing_service=None,
    input_type=_SECUREBULKLOADHFILESREQUEST,
    output_type=_SECUREBULKLOADHFILESRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='CleanupBulkLoad',
    full_name='SecureBulkLoadService.CleanupBulkLoad',
    index=2,
    containing_service=None,
    input_type=_CLEANUPBULKLOADREQUEST,
    output_type=_CLEANUPBULKLOADRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECUREBULKLOADSERVICE)

DESCRIPTOR.services_by_name['SecureBulkLoadService'] = _SECUREBULKLOADSERVICE

# @@protoc_insertion_point(module_scope)
