# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VisibilityLabels.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import Client_pb2 as Client__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='VisibilityLabels.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x16VisibilityLabels.proto\x1a\x0c\x43lient.proto\"=\n\x17VisibilityLabelsRequest\x12\"\n\x08visLabel\x18\x01 \x03(\x0b\x32\x10.VisibilityLabel\"1\n\x0fVisibilityLabel\x12\r\n\x05label\x18\x01 \x02(\x0c\x12\x0f\n\x07ordinal\x18\x02 \x01(\r\"?\n\x18VisibilityLabelsResponse\x12#\n\x06result\x18\x01 \x03(\x0b\x32\x13.RegionActionResult\"-\n\x0fSetAuthsRequest\x12\x0c\n\x04user\x18\x01 \x02(\x0c\x12\x0c\n\x04\x61uth\x18\x02 \x03(\x0c\"0\n\x12UserAuthorizations\x12\x0c\n\x04user\x18\x01 \x02(\x0c\x12\x0c\n\x04\x61uth\x18\x02 \x03(\r\"A\n\x17MultiUserAuthorizations\x12&\n\tuserAuths\x18\x01 \x03(\x0b\x32\x13.UserAuthorizations\"\x1f\n\x0fGetAuthsRequest\x12\x0c\n\x04user\x18\x01 \x02(\x0c\".\n\x10GetAuthsResponse\x12\x0c\n\x04user\x18\x01 \x02(\x0c\x12\x0c\n\x04\x61uth\x18\x02 \x03(\x0c\"\"\n\x11ListLabelsRequest\x12\r\n\x05regex\x18\x01 \x01(\t\"#\n\x12ListLabelsResponse\x12\r\n\x05label\x18\x01 \x03(\x0c\x32\xb7\x02\n\x17VisibilityLabelsService\x12@\n\taddLabels\x12\x18.VisibilityLabelsRequest\x1a\x19.VisibilityLabelsResponse\x12\x37\n\x08setAuths\x12\x10.SetAuthsRequest\x1a\x19.VisibilityLabelsResponse\x12\x39\n\nclearAuths\x12\x10.SetAuthsRequest\x1a\x19.VisibilityLabelsResponse\x12/\n\x08getAuths\x12\x10.GetAuthsRequest\x1a\x11.GetAuthsResponse\x12\x35\n\nlistLabels\x12\x12.ListLabelsRequest\x1a\x13.ListLabelsResponseBL\n*org.apache.hadoop.hbase.protobuf.generatedB\x16VisibilityLabelsProtosH\x01\x88\x01\x01\xa0\x01\x01')
  ,
  dependencies=[Client__pb2.DESCRIPTOR,])




_VISIBILITYLABELSREQUEST = _descriptor.Descriptor(
  name='VisibilityLabelsRequest',
  full_name='VisibilityLabelsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='visLabel', full_name='VisibilityLabelsRequest.visLabel', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=40,
  serialized_end=101,
)


_VISIBILITYLABEL = _descriptor.Descriptor(
  name='VisibilityLabel',
  full_name='VisibilityLabel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='VisibilityLabel.label', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ordinal', full_name='VisibilityLabel.ordinal', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=152,
)


_VISIBILITYLABELSRESPONSE = _descriptor.Descriptor(
  name='VisibilityLabelsResponse',
  full_name='VisibilityLabelsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='VisibilityLabelsResponse.result', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=154,
  serialized_end=217,
)


_SETAUTHSREQUEST = _descriptor.Descriptor(
  name='SetAuthsRequest',
  full_name='SetAuthsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='SetAuthsRequest.user', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='SetAuthsRequest.auth', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=264,
)


_USERAUTHORIZATIONS = _descriptor.Descriptor(
  name='UserAuthorizations',
  full_name='UserAuthorizations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='UserAuthorizations.user', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='UserAuthorizations.auth', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=314,
)


_MULTIUSERAUTHORIZATIONS = _descriptor.Descriptor(
  name='MultiUserAuthorizations',
  full_name='MultiUserAuthorizations',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='userAuths', full_name='MultiUserAuthorizations.userAuths', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=381,
)


_GETAUTHSREQUEST = _descriptor.Descriptor(
  name='GetAuthsRequest',
  full_name='GetAuthsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='GetAuthsRequest.user', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=414,
)


_GETAUTHSRESPONSE = _descriptor.Descriptor(
  name='GetAuthsResponse',
  full_name='GetAuthsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='GetAuthsResponse.user', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='auth', full_name='GetAuthsResponse.auth', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=416,
  serialized_end=462,
)


_LISTLABELSREQUEST = _descriptor.Descriptor(
  name='ListLabelsRequest',
  full_name='ListLabelsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='regex', full_name='ListLabelsRequest.regex', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=464,
  serialized_end=498,
)


_LISTLABELSRESPONSE = _descriptor.Descriptor(
  name='ListLabelsResponse',
  full_name='ListLabelsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='ListLabelsResponse.label', index=0,
      number=1, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=535,
)

_VISIBILITYLABELSREQUEST.fields_by_name['visLabel'].message_type = _VISIBILITYLABEL
_VISIBILITYLABELSRESPONSE.fields_by_name['result'].message_type = Client__pb2._REGIONACTIONRESULT
_MULTIUSERAUTHORIZATIONS.fields_by_name['userAuths'].message_type = _USERAUTHORIZATIONS
DESCRIPTOR.message_types_by_name['VisibilityLabelsRequest'] = _VISIBILITYLABELSREQUEST
DESCRIPTOR.message_types_by_name['VisibilityLabel'] = _VISIBILITYLABEL
DESCRIPTOR.message_types_by_name['VisibilityLabelsResponse'] = _VISIBILITYLABELSRESPONSE
DESCRIPTOR.message_types_by_name['SetAuthsRequest'] = _SETAUTHSREQUEST
DESCRIPTOR.message_types_by_name['UserAuthorizations'] = _USERAUTHORIZATIONS
DESCRIPTOR.message_types_by_name['MultiUserAuthorizations'] = _MULTIUSERAUTHORIZATIONS
DESCRIPTOR.message_types_by_name['GetAuthsRequest'] = _GETAUTHSREQUEST
DESCRIPTOR.message_types_by_name['GetAuthsResponse'] = _GETAUTHSRESPONSE
DESCRIPTOR.message_types_by_name['ListLabelsRequest'] = _LISTLABELSREQUEST
DESCRIPTOR.message_types_by_name['ListLabelsResponse'] = _LISTLABELSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VisibilityLabelsRequest = _reflection.GeneratedProtocolMessageType('VisibilityLabelsRequest', (_message.Message,), dict(
  DESCRIPTOR = _VISIBILITYLABELSREQUEST,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:VisibilityLabelsRequest)
  ))
_sym_db.RegisterMessage(VisibilityLabelsRequest)

VisibilityLabel = _reflection.GeneratedProtocolMessageType('VisibilityLabel', (_message.Message,), dict(
  DESCRIPTOR = _VISIBILITYLABEL,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:VisibilityLabel)
  ))
_sym_db.RegisterMessage(VisibilityLabel)

VisibilityLabelsResponse = _reflection.GeneratedProtocolMessageType('VisibilityLabelsResponse', (_message.Message,), dict(
  DESCRIPTOR = _VISIBILITYLABELSRESPONSE,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:VisibilityLabelsResponse)
  ))
_sym_db.RegisterMessage(VisibilityLabelsResponse)

SetAuthsRequest = _reflection.GeneratedProtocolMessageType('SetAuthsRequest', (_message.Message,), dict(
  DESCRIPTOR = _SETAUTHSREQUEST,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:SetAuthsRequest)
  ))
_sym_db.RegisterMessage(SetAuthsRequest)

UserAuthorizations = _reflection.GeneratedProtocolMessageType('UserAuthorizations', (_message.Message,), dict(
  DESCRIPTOR = _USERAUTHORIZATIONS,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:UserAuthorizations)
  ))
_sym_db.RegisterMessage(UserAuthorizations)

MultiUserAuthorizations = _reflection.GeneratedProtocolMessageType('MultiUserAuthorizations', (_message.Message,), dict(
  DESCRIPTOR = _MULTIUSERAUTHORIZATIONS,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:MultiUserAuthorizations)
  ))
_sym_db.RegisterMessage(MultiUserAuthorizations)

GetAuthsRequest = _reflection.GeneratedProtocolMessageType('GetAuthsRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETAUTHSREQUEST,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:GetAuthsRequest)
  ))
_sym_db.RegisterMessage(GetAuthsRequest)

GetAuthsResponse = _reflection.GeneratedProtocolMessageType('GetAuthsResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETAUTHSRESPONSE,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:GetAuthsResponse)
  ))
_sym_db.RegisterMessage(GetAuthsResponse)

ListLabelsRequest = _reflection.GeneratedProtocolMessageType('ListLabelsRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTLABELSREQUEST,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:ListLabelsRequest)
  ))
_sym_db.RegisterMessage(ListLabelsRequest)

ListLabelsResponse = _reflection.GeneratedProtocolMessageType('ListLabelsResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTLABELSRESPONSE,
  __module__ = 'VisibilityLabels_pb2'
  # @@protoc_insertion_point(class_scope:ListLabelsResponse)
  ))
_sym_db.RegisterMessage(ListLabelsResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\026VisibilityLabelsProtosH\001\210\001\001\240\001\001'))

_VISIBILITYLABELSSERVICE = _descriptor.ServiceDescriptor(
  name='VisibilityLabelsService',
  full_name='VisibilityLabelsService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=538,
  serialized_end=849,
  methods=[
  _descriptor.MethodDescriptor(
    name='addLabels',
    full_name='VisibilityLabelsService.addLabels',
    index=0,
    containing_service=None,
    input_type=_VISIBILITYLABELSREQUEST,
    output_type=_VISIBILITYLABELSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='setAuths',
    full_name='VisibilityLabelsService.setAuths',
    index=1,
    containing_service=None,
    input_type=_SETAUTHSREQUEST,
    output_type=_VISIBILITYLABELSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='clearAuths',
    full_name='VisibilityLabelsService.clearAuths',
    index=2,
    containing_service=None,
    input_type=_SETAUTHSREQUEST,
    output_type=_VISIBILITYLABELSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getAuths',
    full_name='VisibilityLabelsService.getAuths',
    index=3,
    containing_service=None,
    input_type=_GETAUTHSREQUEST,
    output_type=_GETAUTHSRESPONSE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listLabels',
    full_name='VisibilityLabelsService.listLabels',
    index=4,
    containing_service=None,
    input_type=_LISTLABELSREQUEST,
    output_type=_LISTLABELSRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VISIBILITYLABELSSERVICE)

DESCRIPTOR.services_by_name['VisibilityLabelsService'] = _VISIBILITYLABELSSERVICE

# @@protoc_insertion_point(module_scope)
