# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: HFile.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import HBase_pb2 as HBase__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='HFile.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x0bHFile.proto\x1a\x0bHBase.proto\"3\n\rFileInfoProto\x12\"\n\tmap_entry\x18\x01 \x03(\x0b\x32\x0f.BytesBytesPair\"\x91\x03\n\x10\x46ileTrailerProto\x12\x18\n\x10\x66ile_info_offset\x18\x01 \x01(\x04\x12 \n\x18load_on_open_data_offset\x18\x02 \x01(\x04\x12$\n\x1cuncompressed_data_index_size\x18\x03 \x01(\x04\x12 \n\x18total_uncompressed_bytes\x18\x04 \x01(\x04\x12\x18\n\x10\x64\x61ta_index_count\x18\x05 \x01(\r\x12\x18\n\x10meta_index_count\x18\x06 \x01(\r\x12\x13\n\x0b\x65ntry_count\x18\x07 \x01(\x04\x12\x1d\n\x15num_data_index_levels\x18\x08 \x01(\r\x12\x1f\n\x17\x66irst_data_block_offset\x18\t \x01(\x04\x12\x1e\n\x16last_data_block_offset\x18\n \x01(\x04\x12\x1d\n\x15\x63omparator_class_name\x18\x0b \x01(\t\x12\x19\n\x11\x63ompression_codec\x18\x0c \x01(\r\x12\x16\n\x0e\x65ncryption_key\x18\r \x01(\x0c\x42\x41\n*org.apache.hadoop.hbase.protobuf.generatedB\x0bHFileProtosH\x01\x88\x01\x01\xa0\x01\x01')
  ,
  dependencies=[HBase__pb2.DESCRIPTOR,])




_FILEINFOPROTO = _descriptor.Descriptor(
  name='FileInfoProto',
  full_name='FileInfoProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='map_entry', full_name='FileInfoProto.map_entry', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=79,
)


_FILETRAILERPROTO = _descriptor.Descriptor(
  name='FileTrailerProto',
  full_name='FileTrailerProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_info_offset', full_name='FileTrailerProto.file_info_offset', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_on_open_data_offset', full_name='FileTrailerProto.load_on_open_data_offset', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='uncompressed_data_index_size', full_name='FileTrailerProto.uncompressed_data_index_size', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_uncompressed_bytes', full_name='FileTrailerProto.total_uncompressed_bytes', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data_index_count', full_name='FileTrailerProto.data_index_count', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='meta_index_count', full_name='FileTrailerProto.meta_index_count', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='entry_count', full_name='FileTrailerProto.entry_count', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_data_index_levels', full_name='FileTrailerProto.num_data_index_levels', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='first_data_block_offset', full_name='FileTrailerProto.first_data_block_offset', index=8,
      number=9, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='last_data_block_offset', full_name='FileTrailerProto.last_data_block_offset', index=9,
      number=10, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='comparator_class_name', full_name='FileTrailerProto.comparator_class_name', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compression_codec', full_name='FileTrailerProto.compression_codec', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encryption_key', full_name='FileTrailerProto.encryption_key', index=12,
      number=13, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=483,
)

_FILEINFOPROTO.fields_by_name['map_entry'].message_type = HBase__pb2._BYTESBYTESPAIR
DESCRIPTOR.message_types_by_name['FileInfoProto'] = _FILEINFOPROTO
DESCRIPTOR.message_types_by_name['FileTrailerProto'] = _FILETRAILERPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileInfoProto = _reflection.GeneratedProtocolMessageType('FileInfoProto', (_message.Message,), dict(
  DESCRIPTOR = _FILEINFOPROTO,
  __module__ = 'HFile_pb2'
  # @@protoc_insertion_point(class_scope:FileInfoProto)
  ))
_sym_db.RegisterMessage(FileInfoProto)

FileTrailerProto = _reflection.GeneratedProtocolMessageType('FileTrailerProto', (_message.Message,), dict(
  DESCRIPTOR = _FILETRAILERPROTO,
  __module__ = 'HFile_pb2'
  # @@protoc_insertion_point(class_scope:FileTrailerProto)
  ))
_sym_db.RegisterMessage(FileTrailerProto)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n*org.apache.hadoop.hbase.protobuf.generatedB\013HFileProtosH\001\210\001\001\240\001\001'))
# @@protoc_insertion_point(module_scope)
