# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: StorageClusterStatusMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='StorageClusterStatusMessage.proto',
  package='org.apache.hadoop.hbase.rest.protobuf.generated',
  syntax='proto2',
  serialized_pb=_b('\n!StorageClusterStatusMessage.proto\x12/org.apache.hadoop.hbase.rest.protobuf.generated\"\xdb\x05\n\x14StorageClusterStatus\x12]\n\tliveNodes\x18\x01 \x03(\x0b\x32J.org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node\x12\x11\n\tdeadNodes\x18\x02 \x03(\t\x12\x0f\n\x07regions\x18\x03 \x01(\x05\x12\x10\n\x08requests\x18\x04 \x01(\x03\x12\x13\n\x0b\x61verageLoad\x18\x05 \x01(\x01\x1a\xd2\x02\n\x06Region\x12\x0c\n\x04name\x18\x01 \x02(\x0c\x12\x0e\n\x06stores\x18\x02 \x01(\x05\x12\x12\n\nstorefiles\x18\x03 \x01(\x05\x12\x17\n\x0fstorefileSizeMB\x18\x04 \x01(\x05\x12\x16\n\x0ememstoreSizeMB\x18\x05 \x01(\x05\x12\x1c\n\x14storefileIndexSizeMB\x18\x06 \x01(\x05\x12\x19\n\x11readRequestsCount\x18\x07 \x01(\x03\x12\x1a\n\x12writeRequestsCount\x18\x08 \x01(\x03\x12\x17\n\x0frootIndexSizeKB\x18\t \x01(\x05\x12\x1e\n\x16totalStaticIndexSizeKB\x18\n \x01(\x05\x12\x1e\n\x16totalStaticBloomSizeKB\x18\x0b \x01(\x05\x12\x1a\n\x12totalCompactingKVs\x18\x0c \x01(\x03\x12\x1b\n\x13\x63urrentCompactedKVs\x18\r \x01(\x03\x1a\xc3\x01\n\x04Node\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x11\n\tstartCode\x18\x02 \x01(\x03\x12\x10\n\x08requests\x18\x03 \x01(\x03\x12\x12\n\nheapSizeMB\x18\x04 \x01(\x05\x12\x15\n\rmaxHeapSizeMB\x18\x05 \x01(\x05\x12]\n\x07regions\x18\x06 \x03(\x0b\x32L.org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region')
)




_STORAGECLUSTERSTATUS_REGION = _descriptor.Descriptor(
  name='Region',
  full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.name', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stores', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.stores', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storefiles', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.storefiles', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storefileSizeMB', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.storefileSizeMB', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memstoreSizeMB', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.memstoreSizeMB', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='storefileIndexSizeMB', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.storefileIndexSizeMB', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readRequestsCount', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.readRequestsCount', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='writeRequestsCount', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.writeRequestsCount', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rootIndexSizeKB', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.rootIndexSizeKB', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalStaticIndexSizeKB', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.totalStaticIndexSizeKB', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalStaticBloomSizeKB', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.totalStaticBloomSizeKB', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='totalCompactingKVs', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.totalCompactingKVs', index=11,
      number=12, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currentCompactedKVs', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region.currentCompactedKVs', index=12,
      number=13, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=620,
)

_STORAGECLUSTERSTATUS_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startCode', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node.startCode', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requests', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node.requests', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='heapSizeMB', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node.heapSizeMB', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxHeapSizeMB', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node.maxHeapSizeMB', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regions', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node.regions', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=818,
)

_STORAGECLUSTERSTATUS = _descriptor.Descriptor(
  name='StorageClusterStatus',
  full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='liveNodes', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.liveNodes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='deadNodes', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.deadNodes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='regions', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.regions', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requests', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.requests', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='averageLoad', full_name='org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.averageLoad', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_STORAGECLUSTERSTATUS_REGION, _STORAGECLUSTERSTATUS_NODE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=818,
)

_STORAGECLUSTERSTATUS_REGION.containing_type = _STORAGECLUSTERSTATUS
_STORAGECLUSTERSTATUS_NODE.fields_by_name['regions'].message_type = _STORAGECLUSTERSTATUS_REGION
_STORAGECLUSTERSTATUS_NODE.containing_type = _STORAGECLUSTERSTATUS
_STORAGECLUSTERSTATUS.fields_by_name['liveNodes'].message_type = _STORAGECLUSTERSTATUS_NODE
DESCRIPTOR.message_types_by_name['StorageClusterStatus'] = _STORAGECLUSTERSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StorageClusterStatus = _reflection.GeneratedProtocolMessageType('StorageClusterStatus', (_message.Message,), dict(

  Region = _reflection.GeneratedProtocolMessageType('Region', (_message.Message,), dict(
    DESCRIPTOR = _STORAGECLUSTERSTATUS_REGION,
    __module__ = 'StorageClusterStatusMessage_pb2'
    # @@protoc_insertion_point(class_scope:org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Region)
    ))
  ,

  Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), dict(
    DESCRIPTOR = _STORAGECLUSTERSTATUS_NODE,
    __module__ = 'StorageClusterStatusMessage_pb2'
    # @@protoc_insertion_point(class_scope:org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus.Node)
    ))
  ,
  DESCRIPTOR = _STORAGECLUSTERSTATUS,
  __module__ = 'StorageClusterStatusMessage_pb2'
  # @@protoc_insertion_point(class_scope:org.apache.hadoop.hbase.rest.protobuf.generated.StorageClusterStatus)
  ))
_sym_db.RegisterMessage(StorageClusterStatus)
_sym_db.RegisterMessage(StorageClusterStatus.Region)
_sym_db.RegisterMessage(StorageClusterStatus.Node)


# @@protoc_insertion_point(module_scope)
